// Generates src/environments/environment.ts (dev) or environment.prod.ts
// (production, picked up by angular.json's `production` fileReplacements)
// from process.env. Mirrors apps/landing/mynode.js's convention — that whole
// directory is gitignored (**/src/environments/**), so this file is the only
// reproducible way to build this app outside of a hand-maintained local copy.
const fs = require('fs');
const path = require('path');

const isProduction = process.env.NODE_ENV === 'production';

// Reads plain `KEY=value` lines into process.env, never overriding a value
// already set there (matches dotenv's own precedence: real env/build-args
// win over the file). Not the `dotenv` package — it isn't one of this
// workspace's dependencies, and this only ever needs the simple case.
function loadEnvFile(envPath) {
  if (!fs.existsSync(envPath)) return;
  for (const line of fs.readFileSync(envPath, 'utf8').split('\n')) {
    const match = /^\s*([\w.-]+)\s*=\s*(.*)?\s*$/.exec(line);
    if (match && !(match[1] in process.env)) {
      process.env[match[1]] = (match[2] || '').replace(/^["']|["']$/g, '');
    }
  }
}

if (isProduction) {
  // Dockerfile.ideploy-web copies the server's own .env into this
  // directory before running the build (COPY .env .env, same spot
  // apps/landing's Dockerfile copies its .env for mynode.js to read) —
  // load it from right here, not the repo root.
  loadEnvFile(path.join(__dirname, '../.env'));
} else {
  // Dev only: docker-compose.dev.yml's `ideploy-api`/`soketi` services both
  // read PUSHER_APP_KEY from this same repo-root file, so the browser has to
  // use the identical value or every websocket subscribe fails immediately
  // with "App key … does not exist" (code 4001) — this silently broke once
  // already (see git history on this file) from a generated key drifting out
  // of sync with a hand-edited environment.ts. Not required: a bare host
  // checkout without .env.dev still gets a working (if key-less) build via
  // the fallbacks below.
  loadEnvFile(path.join(__dirname, '../../../.env.dev'));
}

// No guessed domain defaults in production, unlike the dev fallbacks below —
// a wrong guess would silently ship a build that talks to the wrong backend.
const requiredInProd = ['IDEPLOY_API_URL', 'SERVICES_API_URL', 'SERVICES_DASHBOARD_URL', 'PUSHER_APP_KEY'];
if (isProduction) {
  const missing = requiredInProd.filter((v) => !process.env[v]);
  if (missing.length > 0) {
    console.error(`\n❌ Missing required environment variables for a production build:`);
    missing.forEach((v) => console.error(`   - ${v}`));
    console.error(`\nSet them in the .env copied into the image, or pass them as Docker build-args (see Dockerfile/prod/Dockerfile.ideploy-web).\n`);
    process.exit(1);
  }
}

const content = `// AUTO-GENERATED by scripts/set-env.js — do not edit by hand.
// Regenerate with: npm run ${isProduction ? 'env:prod' : 'env:dev'}

export const environment = {
  production: ${isProduction},
  api: {
    url: '${process.env.IDEPLOY_API_URL || 'http://localhost:3002'}',
    version: '${process.env.IDEPLOY_API_VERSION || 'v1'}',
  },
  services: {
    api: {
      url: '${process.env.SERVICES_API_URL || 'http://localhost:3001'}',
    },
    console: {
      url: '${process.env.SERVICES_DASHBOARD_URL || 'http://localhost:4200'}',
    },
  },
  realtime: {
    key: '${process.env.PUSHER_APP_KEY || ''}',
    wsHost: '${process.env.PUSHER_HOST || 'localhost'}',
    wsPort: ${process.env.PUSHER_PORT || 6001},
    forceTLS: ${(process.env.PUSHER_SCHEME || 'http') === 'https'},
  },
};
`;

const outDir = path.join(__dirname, '../src/environments');
fs.mkdirSync(outDir, { recursive: true });
const outFile = path.join(outDir, isProduction ? 'environment.prod.ts' : 'environment.ts');
fs.writeFileSync(outFile, content);
console.log(`✅ Wrote ${path.relative(process.cwd(), outFile)}`);
