import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  inject,
  signal,
  AfterViewInit,
  OnDestroy,
  PLATFORM_ID,
  ViewChild,
  NgZone,
} from '@angular/core';
import { CommonModule, isPlatformBrowser } from '@angular/common';
import { RouterLink } from '@angular/router';

interface Stage {
  readonly step: string;
  readonly title: string;
  readonly caption: string;
  readonly price: string;
  readonly ctaLabel: string;
  readonly link: string;
  readonly image: string;
  readonly imageAlt: string;
}

@Component({
  selector: 'app-journey',
  imports: [CommonModule, RouterLink],
  changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: './journey.html',
  styleUrl: './journey.css',
})
export class JourneyComponent implements AfterViewInit, OnDestroy {
  private readonly platformId = inject(PLATFORM_ID);
  private readonly zone = inject(NgZone);

  @ViewChild('scrollContainer') scrollContainerRef!: ElementRef<HTMLElement>;

  /** Index of the currently visible stage (0 = intro, 1..N = stages, N+1 = outro). */
  protected readonly activeIndex = signal(0);

  /** Total number of snap sections (intro + stages + outro). */
  protected get totalSections(): number {
    return this.stages.length + 2; // intro + stages + outro
  }

  private observer?: IntersectionObserver;

  private readonly seePricing = $localize`:@@journey.pricingCta:See pricing`;

  protected readonly stages: readonly Stage[] = [
    {
      step: $localize`:@@what-is-idem.step.brand.label:Brand`,
      title: $localize`:@@services.brand.name:Brand identity`,
      caption: $localize`:@@journey.brand.caption:Her logo, brand guidelines and business cards, ready in minutes.`,
      price: $localize`:@@services.brand.price:Identity Pack from 1,999 F`,
      ctaLabel: $localize`:@@services.brand.cta:Create my brand`,
      link: '/pricing',
      image: 'assets/images/home/brand.webp',
      imageAlt: $localize`:@@services.brand.alt:IDEM brand studio: generated logo concepts and OKLCH color palette`,
    },
    {
      step: $localize`:@@what-is-idem.step.strategy.label:Strategy`,
      title: $localize`:@@journey.strategy.title:Business plan & pitch deck`,
      caption: $localize`:@@journey.strategy.caption:A structured business plan and an investor pitch deck, ready to present.`,
      price: $localize`:@@services.strategy.price:Strategy Pack from 2,999 F`,
      ctaLabel: $localize`:@@services.strategy.cta:Build my plan`,
      link: '/pricing',
      image: 'assets/images/home/bp.webp',
      imageAlt: $localize`:@@services.strategy.alt:IDEM business plan dashboard with financial projections and OHADA compliance`,
    },
    {
      step: $localize`:@@journey.step.finance:Finances`,
      title: $localize`:@@journey.finance.title:Financial projections`,
      caption: $localize`:@@journey.finance.caption:3-year forecasts, then plan vs actuals tracked month by month.`,
      price: $localize`:@@journey.finance.price:Included in the Strategy Pack`,
      ctaLabel: this.seePricing,
      link: '/pricing',
      image: 'assets/images/home/bp.webp',
      imageAlt: $localize`:@@journey.finance.alt:IDEM financial projections and 3-year revenue forecast dashboard`,
    },
    {
      step: $localize`:@@journey.step.legal:Legal`,
      title: $localize`:@@journey.legal.title:OHADA legal kit`,
      caption: $localize`:@@journey.legal.caption:Articles, shareholder agreement and T&Cs, compliant with OHADA law.`,
      price: $localize`:@@journey.legal.price:Compliance Pack from 2,499 F`,
      ctaLabel: this.seePricing,
      link: '/pricing',
      image: 'assets/images/home/logo_gen.webp',
      imageAlt: $localize`:@@journey.legal.alt:OHADA legal document kit and articles of association generator`,
    },
    {
      step: $localize`:@@journey.step.media:Communication`,
      title: 'IDEM Media',
      caption: $localize`:@@journey.media.caption:Communication strategy, editorial calendar and one-click publishing of flyers and videos to her networks.`,
      price: $localize`:@@offer.media.price:1,999–4,999 F/mo`,
      ctaLabel: this.seePricing,
      link: '/pricing',
      image: 'assets/images/home/lbg2.webp',
      imageAlt: $localize`:@@journey.media.alt:IDEM Media social editorial calendar and content publisher`,
    },
    {
      step: $localize`:@@what-is-idem.step.product.label:Product`,
      title: 'iCode',
      caption: $localize`:@@journey.code.caption:Her online shop, generated from a sentence and editable live.`,
      price: $localize`:@@services.code.price:Free to generate · Project Pass 999 F`,
      ctaLabel: $localize`:@@services.code.cta:Discover iCode`,
      link: '/idev',
      image: 'assets/images/home/ideo.webp',
      imageAlt: $localize`:@@services.code.alt:iCode editor with a live web-app preview generated by AI`,
    },
    {
      step: $localize`:@@what-is-idem.step.deploy.label:Deploy`,
      title: 'iDeploy',
      caption: $localize`:@@journey.deploy.caption:Her site goes live on cafe.idem.africa, free domain and SSL.`,
      price: $localize`:@@services.deploy.price:5 deployments free`,
      ctaLabel: $localize`:@@services.deploy.cta:Deploy with iDeploy`,
      link: '/ideploy',
      image: 'assets/images/home/diagram.webp',
      imageAlt: $localize`:@@services.deploy.alt:iDeploy console: domain management, one-click deploy status and server metrics`,
    },
    {
      step: $localize`:@@what-is-idem.step.support.label:Support`,
      title: 'IDEM Conseil',
      caption: $localize`:@@journey.conseil.caption:A certified advisor helps her land her first financing.`,
      price: $localize`:@@services.conseil.price:from 2,500 F/mo`,
      ctaLabel: $localize`:@@services.conseil.cta:Talk to an advisor`,
      link: '/contact',
      image: 'assets/images/home/lbg2.webp',
      imageAlt: $localize`:@@services.conseil.alt:IDEM Conseil portal: certified advisor profiles and investor-matching dashboard`,
    },
  ];

  ngAfterViewInit(): void {
    if (!isPlatformBrowser(this.platformId)) return;

    // Run IntersectionObserver outside Angular zone for performance
    this.zone.runOutsideAngular(() => {
      const container = this.scrollContainerRef.nativeElement;
      const sections = container.querySelectorAll('.jn-snap-section');

      this.observer = new IntersectionObserver(
        (entries) => {
          for (const entry of entries) {
            if (entry.isIntersecting && entry.intersectionRatio >= 0.5) {
              const idx = Number((entry.target as HTMLElement).dataset['sectionIndex']);
              if (!isNaN(idx)) {
                this.zone.run(() => this.activeIndex.set(idx));
              }
            }
          }
        },
        {
          root: container,
          threshold: 0.5,
        }
      );

      sections.forEach((s) => this.observer!.observe(s));
    });
  }

  ngOnDestroy(): void {
    this.observer?.disconnect();
  }

  /** Progress as 0..100 for the top bar. */
  protected get progressPercent(): number {
    const total = this.totalSections - 1;
    return total > 0 ? (this.activeIndex() / total) * 100 : 0;
  }
}
