<?php

namespace App\Jobs\Security;

use App\Models\Application;
use App\Models\Server;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;

/**
 * Configure Traefik to write JSON access logs for CrowdSec parser
 * 
 * This job:
 * 1. Creates /var/log/traefik directory
 * 2. Configures Traefik dynamic config for JSON logs
 * 3. Reloads Traefik to apply changes
 */
class ConfigureTraefikLoggingJob implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    public $tries = 1;
    public $timeout = 120;

    public function __construct(
        public Server $server
    ) {}

    public function handle(): void
    {
        ray("Configuring Traefik logging on server: {$this->server->name}");
        
        try {
            // 1. Create log directory
            $this->createLogDirectory();
            
            // 2. Configure Traefik for JSON access logs
            $this->configureTraefikAccessLogs();
            
            // 3. Verify logs are being written
            sleep(5);
            $this->verifyLogs();
            
            // 4. Update server metadata
            $this->server->update([
                'traefik_logging_enabled' => true,
            ]);
            
            ray("✅ Traefik logging configured successfully");
            
        } catch (\Exception $e) {
            ray("❌ Failed to configure Traefik logging: {$e->getMessage()}");
            throw $e;
        }
    }
    
    private function createLogDirectory(): void
    {
        ray("Creating /var/log/traefik directory...");
        
        instant_remote_process([
            'mkdir -p /var/log/traefik',
            'chmod 755 /var/log/traefik',
            'touch /var/log/traefik/access.log',
            'chmod 644 /var/log/traefik/access.log',
        ], $this->server);
    }
    
    private function configureTraefikAccessLogs(): void
    {
        ray("Configuring Traefik access logs...");
        
        // Traefik config file content
        $config = <<<'YAML'
# CrowdSec Integration - Access Logs
# Auto-generated by iDeploy
accessLog:
  filePath: "/var/log/traefik/access.log"
  format: json
  bufferingSize: 0
  fields:
    defaultMode: keep
    names: {}
    headers:
      defaultMode: keep
      names: {}
YAML;
        
        // Write config locally
        $tempFile = storage_path("app/traefik-logging-{$this->server->id}.yml");
        file_put_contents($tempFile, $config);
        
        // Upload to Traefik dynamic config directory
        instant_scp(
            $tempFile,
            '/data/coolify/proxy/dynamic/crowdsec-logging.yml',
            $this->server
        );
        
        // Cleanup
        @unlink($tempFile);
        
        // Reload Traefik to apply config
        ray("Reloading Traefik...");
        instant_remote_process([
            'docker exec coolify-proxy kill -SIGHUP 1',
        ], $this->server);
        
        ray("Traefik config uploaded and reloaded");
    }
    
    private function verifyLogs(): void
    {
        ray("Verifying logs are being written...");
        
        // Make a test request to generate a log entry
        $output = instant_remote_process([
            'curl -s -o /dev/null http://localhost',
            'sleep 2',
            'test -f /var/log/traefik/access.log && echo "LOG_EXISTS" || echo "LOG_MISSING"',
            'ls -lh /var/log/traefik/access.log || true',
        ], $this->server);
        
        if (!str_contains($output, 'LOG_EXISTS')) {
            throw new \Exception('Traefik access log file not created');
        }
        
        ray("✅ Log file exists: " . trim($output));
    }
    
    public function failed(\Throwable $exception): void
    {
        ray("ConfigureTraefikLoggingJob failed: {$exception->getMessage()}");
        
        $this->server->update([
            'traefik_logging_enabled' => false,
        ]);
    }
}
