import { ChangeDetectionStrategy, Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink } from '@angular/router';
import { environment } from '../../../environments/environment';

interface ShowcaseService {
  readonly id: string;
  readonly kicker: string;
  readonly title: string;
  readonly description: string;
  readonly features: readonly string[];
  readonly priceLine: string;
  readonly ctaLabel: string;
  readonly link: string;
  readonly external: boolean;
  readonly image: string;
  readonly imageAlt: string;
  /** UI accent hue used for the chrome + soft glow behind the frame. */
  readonly accent: 'primary' | 'accent' | 'secondary' | 'success';
}

@Component({
  selector: 'app-services-showcase',
  imports: [CommonModule, RouterLink],
  changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: './services-showcase.html',
  styleUrl: './services-showcase.css',
})
export class ServicesShowcaseComponent {
  private readonly dashboardUrl = environment.services.dashboard.url;
  private readonly idevUrl = environment.services.idev.url;
  private readonly ideployUrl = environment.services.ideploy.url;

  protected readonly services: readonly ShowcaseService[] = [
    {
      id: 'brand',
      kicker: $localize`:@@services.brand.kicker:IDEM Business · Identity`,
      title: $localize`:@@services.brand.title:A professional brand in minutes`,
      description: $localize`:@@services.brand.description:Vector logo, complete brand guidelines and customizable business cards. The credibility investors and clients see first, generated and yours to export.`,
      features: [
        $localize`:@@services.brand.f1:Vector logo, several concepts`,
        $localize`:@@services.brand.f2:OKLCH palette + typography scale`,
        $localize`:@@services.brand.f3:Exportable brand kit`,
      ],
      priceLine: $localize`:@@services.brand.price:Identity Pack from 1,999 F`,
      ctaLabel: $localize`:@@services.brand.cta:Create my brand`,
      link: `${this.dashboardUrl}/create-project`,
      external: true,
      image: 'assets/images/home/brand_showcase.webp',
      imageAlt: $localize`:@@services.brand.alt:IDEM brand studio: generated logo concepts, OKLCH color palette and typographic scale`,
      accent: 'accent',
    },
    {
      id: 'strategy',
      kicker: $localize`:@@services.strategy.kicker:IDEM Business · Strategy`,
      title: $localize`:@@services.strategy.title:An investor-ready business plan`,
      description: $localize`:@@services.strategy.description:Market analysis, 3-year forecasts tracked over time, pitch deck and OHADA-compliant legal kit. The structured file that turns an idea into a fundable project.`,
      features: [
        $localize`:@@services.strategy.f1:Business plan + investor pitch deck`,
        $localize`:@@services.strategy.f2:Financial forecasts, plan vs actuals`,
        $localize`:@@services.strategy.f3:OHADA legal kit (articles, T&Cs)`,
      ],
      priceLine: $localize`:@@services.strategy.price:Strategy Pack from 2,999 F · full pack 4,999 F`,
      ctaLabel: $localize`:@@services.strategy.cta:Build my plan`,
      link: `${this.dashboardUrl}/create-project`,
      external: true,
      image: 'assets/images/home/bp_showcase.webp',
      imageAlt: $localize`:@@services.strategy.alt:IDEM business plan dashboard with financial projections, OHADA compliance and AI recommendations`,
      accent: 'primary',
    },
    {
      id: 'appgen',
      kicker: $localize`:@@services.appgen.kicker:IDEV · App generation`,
      title: $localize`:@@services.appgen.title:Describe it, watch the app run`,
      description: $localize`:@@services.appgen.description:Full-stack code generated from a sentence, running live in your browser. Generating is free; you pay only to own it, download the code or push to GitHub.`,
      features: [
        $localize`:@@services.appgen.f1:Full-stack React, Node & more`,
        $localize`:@@services.appgen.f2:Real-time preview in the browser`,
        $localize`:@@services.appgen.f3:Code export + GitHub push`,
      ],
      priceLine: $localize`:@@services.appgen.price:Free to generate · Project Pass 999 F to own`,
      ctaLabel: $localize`:@@services.appgen.cta:Discover IDEV`,
      link: '/idev',
      external: false,
      image: 'assets/images/home/appgen_showcase.webp',
      imageAlt: $localize`:@@services.appgen.alt:IDEV code editor with live web-app preview generated by AI`,
      accent: 'primary',
    },
    {
      id: 'ideploy',
      kicker: $localize`:@@services.ideploy.kicker:iDeploy · Hosting`,
      title: $localize`:@@services.ideploy.title:In production in one click, hosted in Africa`,
      description: $localize`:@@services.ideploy.description:Every app ships with a free monapp.idem.africa domain, automatic SSL, live logs and monitoring. Deploy on our servers or your own, no DevOps required.`,
      features: [
        $localize`:@@services.ideploy.f1:Free .idem.africa domain + auto SSL`,
        $localize`:@@services.ideploy.f2:Live logs, metrics, 1-click redeploy`,
        $localize`:@@services.ideploy.f3:Our servers or yours (BYOS)`,
      ],
      priceLine: $localize`:@@services.ideploy.price:5 deployments free, then from 100 F`,
      ctaLabel: $localize`:@@services.ideploy.cta:Deploy with iDeploy`,
      link: '/ideploy',
      external: false,
      image: 'assets/images/home/ideploy_showcase.webp',
      imageAlt: $localize`:@@services.ideploy.alt:iDeploy cloud console: domain management, one-click deploy status, live logs and server metrics`,
      accent: 'success',
    },
    {
      id: 'conseil',
      kicker: $localize`:@@services.conseil.kicker:IDEM Conseil · Human support`,
      title: $localize`:@@services.conseil.title:AI does 80%, humans do the 20% that count`,
      description: $localize`:@@services.conseil.description:Certified local advisors pick up where the AI stops: business diagnosis, human review of your deliverables, and introductions to banks, incubators and investors.`,
      features: [
        $localize`:@@services.conseil.f1:Certified advisors, in person`,
        $localize`:@@services.conseil.f2:Monthly workshops + 1:1 sessions`,
        $localize`:@@services.conseil.f3:Funding & investor matching`,
      ],
      priceLine: $localize`:@@services.conseil.price:Standard 2,500 F · Premium 10,000 F · Gold 15,000 F / month`,
      ctaLabel: $localize`:@@services.conseil.cta:Talk to an advisor`,
      link: '/contact',
      external: false,
      image: 'assets/images/home/conseil_showcase.webp',
      imageAlt: $localize`:@@services.conseil.alt:IDEM Conseil portal: certified advisor profiles, review calendar and investor-matching dashboard`,
      accent: 'accent',
    },
  ];
}
