/**
 * Les deux capacités GLM qui ne passent pas par le contrat OpenAI : générer une
 * image, et lire une image.
 *
 * Z.ai sert la génération d'image sur son propre endpoint (`/images/generations`)
 * et la vision par le chat multimodal. Ni l'un ni l'autre n'entre dans le
 * `PromptService`, bâti autour de la complétion de texte — d'où ce module, seul
 * endroit où vivent ces appels. Quatre services en avaient besoin ; les y
 * laisser aurait dupliqué quatre fois la même plomberie HTTP, ses en-têtes et
 * ses replis.
 */

import axios from 'axios';

import { GLM_ENDPOINTS, getGlmApiKey } from '../config/ai-providers.config';
import { AI_CONFIG, GLM_MODELS } from '../config/ai.config';
import logger from '../config/logger';

export interface GeneratedImage {
  buffer: Buffer;
  mimeType: string;
  /** Modèle qui a réellement produit l'image (principal ou repli). */
  model: string;
}

export interface GenerateImageOptions {
  /** Format demandé, ex. `1344x768`. Défaut : paysage. */
  size?: string;
  model?: string;
  fallbackModel?: string;
  /** Étiquette de journalisation, pour retrouver l'appel dans les traces. */
  tag?: string;
}

export interface AnalyzeImageOptions {
  model?: string;
  fallbackModel?: string;
  maxOutputTokens?: number;
  temperature?: number;
}

/** Vrai si le fournisseur est configuré ; sinon rien n'est tenté. */
export function isGlmConfigured(): boolean {
  return Boolean(getGlmApiKey());
}

/**
 * Génère une image et rend ses octets.
 *
 * Bascule sur le modèle de repli si le principal échoue : la saturation est par
 * MODÈLE, rejouer le même ne mènerait à rien.
 */
export async function generateImage(
  prompt: string,
  options: GenerateImageOptions = {},
): Promise<GeneratedImage> {
  const apiKey = requireKey();
  const model = options.model ?? GLM_MODELS.image;
  const fallbackModel = options.fallbackModel ?? GLM_MODELS.imageFallback;
  const attempt = async (candidate: string): Promise<GeneratedImage> => {
    const started = Date.now();
    const response = await axios.post<{ data?: { url?: string; b64_json?: string }[] }>(
      GLM_ENDPOINTS.images,
      { model: candidate, prompt, size: options.size ?? landscapeFor(candidate) },
      { headers: { Authorization: `Bearer ${apiKey}` }, timeout: IMAGE_TIMEOUT_MS },
    );

    const entry = response.data?.data?.[0];
    const buffer = entry?.b64_json
      ? Buffer.from(entry.b64_json, 'base64')
      : entry?.url
        ? await download(entry.url)
        : null;

    if (!buffer) {
      throw new Error(`${candidate} did not return an image`);
    }

    logger.info(`[GLM] image generated by ${candidate}`, {
      tag: options.tag,
      durationMs: Date.now() - started,
      bytes: buffer.length,
    });
    return { buffer, mimeType: 'image/png', model: candidate };
  };

  try {
    return await attempt(model);
  } catch (error: any) {
    if (fallbackModel === model) {
      throw error;
    }
    logger.warn(`[GLM] ${model} failed (${error?.message}) — falling back to ${fallbackModel}`);
    return attempt(fallbackModel);
  }
}

/**
 * Lit une image et rend la réponse texte du modèle.
 *
 * GLM suit ici le contrat OpenAI : une partie `image_url` portant une data URI,
 * à côté de la consigne. Le raisonnement est coupé — il se décompte du budget
 * de sortie, et sur le petit JSON qu'on attend il le viderait.
 */
export async function analyzeImage(
  base64: string,
  mimeType: string,
  instruction: string,
  options: AnalyzeImageOptions = {},
): Promise<string> {
  const apiKey = requireKey();
  const model = options.model ?? GLM_MODELS.vision;
  const fallbackModel = options.fallbackModel ?? VISION_FALLBACK_MODEL;

  const attempt = async (candidate: string): Promise<string> => {
    const response = await axios.post<{ choices?: { message?: { content?: string } }[] }>(
      `${GLM_ENDPOINTS.base}/chat/completions`,
      {
        model: candidate,
        messages: [
          {
            role: 'user',
            content: [
              { type: 'image_url', image_url: { url: `data:${mimeType};base64,${base64}` } },
              { type: 'text', text: instruction },
            ],
          },
        ],
        max_tokens: options.maxOutputTokens ?? 1500,
        temperature: options.temperature ?? 0.1,
        thinking: { type: 'disabled' },
      },
      { headers: { Authorization: `Bearer ${apiKey}` }, timeout: VISION_TIMEOUT_MS },
    );
    return response.data?.choices?.[0]?.message?.content?.trim() ?? '';
  };

  try {
    return await attempt(model);
  } catch (error: any) {
    if (fallbackModel === model) {
      throw error;
    }
    logger.warn(`[GLM] vision failed on ${model} (${error?.message}) — trying ${fallbackModel}`);
    return attempt(fallbackModel);
  }
}

// ---------------------------------------------------------------------------

/**
 * Les deux modèles n'acceptent pas les mêmes dimensions : `glm-image` veut des
 * côtés de 1024 à 2048 divisibles par 32, `cogview-4` de 512 à 2048 divisibles
 * par 16. Un format valide pour l'un est refusé par l'autre — d'où une taille
 * par modèle, et non une constante unique.
 */
const LANDSCAPE_SIZE: Record<string, string> = {
  'glm-image': '1728x960',
  'cogview-4-250304': '1344x768',
};

/** Format retenu quand l'appelant n'en impose pas, pour le modèle visé. */
function landscapeFor(model: string): string {
  return LANDSCAPE_SIZE[model] ?? '1344x768';
}
const IMAGE_TIMEOUT_MS = 120_000;
const VISION_TIMEOUT_MS = 60_000;

/** Repli vision : le modèle gratuit de la même famille. */
const VISION_FALLBACK_MODEL =
  AI_CONFIG.communication.imageSourcing.visionFallbackModel ?? 'glm-4.6v-flash';

function requireKey(): string {
  const apiKey = getGlmApiKey();
  if (!apiKey) {
    throw new Error('GLM_API_KEY is not configured — GLM media calls are unavailable');
  }
  return apiKey;
}

async function download(url: string): Promise<Buffer> {
  const file = await axios.get<ArrayBuffer>(url, {
    responseType: 'arraybuffer',
    timeout: IMAGE_TIMEOUT_MS,
  });
  return Buffer.from(file.data);
}
