/**
 * Referme le balisage d'une section avant qu'elle ne rejoigne le document PDF.
 *
 * ── LE DÉFAUT QUE CECI CORRIGE ──────────────────────────────────────────────
 *
 * Les sections d'un document à pages fixes (charte, deck) sont CONCATÉNÉES dans
 * un seul document HTML. Une section rédigée par le modèle qui oublie de fermer
 * deux `<div>` garde donc ouverts les conteneurs qu'elle a ouverts, et tout ce
 * qui suit s'y range : la page de signature « Generated by Idem » s'est ainsi
 * retrouvée coincée dans la dernière colonne de la page de direction artistique,
 * qui sortait une seconde fois en fin de charte avec la signature par-dessus.
 *
 * Une fermeture en trop produit l'effet inverse : elle referme le conteneur de
 * page qui l'enveloppe, et la section suivante se colle à celle-ci.
 *
 * On équilibre donc chaque section SEULE : les fermetures orphelines sont
 * retirées, les ouvertures restées sans fermeture sont refermées à la fin. Le
 * contenu n'est pas réinterprété — seules des balises de fermeture sont
 * ajoutées ou retirées.
 */

const VOID_ELEMENTS = new Set([
  'area',
  'base',
  'br',
  'col',
  'embed',
  'hr',
  'img',
  'input',
  'link',
  'meta',
  'param',
  'source',
  'track',
  'wbr',
]);

/** Éléments dont le contenu est du texte brut : aucune balise n'y est lue. */
const RAW_TEXT_ELEMENTS = new Set(['script', 'style', 'textarea', 'title']);

const TOKEN = /<!--[\s\S]*?-->|<(\/?)([a-zA-Z][\w:-]*)((?:[^>"']|"[^"]*"|'[^']*')*)>/g;

export function balanceHtmlFragment(html: string): string {
  if (!html || html.indexOf('<') === -1) return html;

  const stack: string[] = [];
  let output = '';
  let cursor = 0;
  let match: RegExpExecArray | null;

  TOKEN.lastIndex = 0;
  while ((match = TOKEN.exec(html)) !== null) {
    const [whole, closing, rawName, attributes] = match;
    output += html.slice(cursor, match.index);
    cursor = match.index + whole.length;

    // Commentaire : recopié tel quel.
    if (!rawName) {
      output += whole;
      continue;
    }

    const name = rawName.toLowerCase();

    if (!closing) {
      output += whole;
      const selfClosing = /\/\s*$/.test(attributes ?? '');
      if (VOID_ELEMENTS.has(name) || selfClosing) continue;

      if (RAW_TEXT_ELEMENTS.has(name)) {
        // Le contenu d'un script ou d'un style est recopié jusqu'à SA fermeture :
        // un `</div>` écrit dans une chaîne JavaScript n'est pas une balise.
        const end = html.toLowerCase().indexOf(`</${name}`, cursor);
        if (end === -1) {
          output += html.slice(cursor) + `</${name}>`;
          cursor = html.length;
          TOKEN.lastIndex = cursor;
          continue;
        }
        const close = html.indexOf('>', end);
        const stop = close === -1 ? html.length : close + 1;
        output += html.slice(cursor, stop);
        cursor = stop;
        TOKEN.lastIndex = cursor;
        continue;
      }

      stack.push(name);
      continue;
    }

    // Fermeture sans ouverture correspondante : retirée.
    const openIndex = stack.lastIndexOf(name);
    if (openIndex === -1) continue;

    // Fermeture d'un parent : les enfants restés ouverts sont refermés d'abord.
    while (stack.length > openIndex + 1) {
      output += `</${stack.pop()}>`;
    }
    stack.pop();
    output += whole;
  }

  output += html.slice(cursor);
  while (stack.length > 0) {
    output += `</${stack.pop()}>`;
  }
  return output;
}
