name: Deploy iDeploy web

on:
  push:
    branches: [main, dev]
    paths:
      - 'apps/ideploy-web/**'
      - 'packages/**'
      - 'Dockerfile/prod/Dockerfile.ideploy-web'
      - '.github/workflows/deploy-ideploy-web.yml'
      - '.github/workflows/_service.yml'
      - 'package.json'
      - 'package-lock.json'
  pull_request:
    branches: [main, dev]
    paths:
      - 'apps/ideploy-web/**'
      - 'packages/**'
      - 'Dockerfile/prod/Dockerfile.ideploy-web'
      - '.github/workflows/deploy-ideploy-web.yml'
      - '.github/workflows/_service.yml'
      - 'package.json'
      - 'package-lock.json'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  service:
    uses: ./.github/workflows/_service.yml
    with:
      image: ideploy-web
      dockerfile: Dockerfile/prod/Dockerfile.ideploy-web
      service: ideploy-web
      build-env: true
      deploy: true
      free-disk: false
    secrets: inherit
