name: Deploy Landing

on:
  push:
    branches: [main, dev]
    paths:
      - 'apps/landing/**'
      - 'packages/**'
      - 'Dockerfile/prod/Dockerfile.landing'
      - '.github/workflows/deploy-landing.yml'
      - '.github/workflows/_service.yml'
      - 'package.json'
      - 'package-lock.json'
  pull_request:
    branches: [main, dev]
    paths:
      - 'apps/landing/**'
      - 'packages/**'
      - 'Dockerfile/prod/Dockerfile.landing'
      - '.github/workflows/deploy-landing.yml'
      - '.github/workflows/_service.yml'
      - 'package.json'
      - 'package-lock.json'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  service:
    uses: ./.github/workflows/_service.yml
    with:
      image: idem-landing
      dockerfile: Dockerfile/prod/Dockerfile.landing
      service: idem-landing
      build-env: true
      deploy: true
      free-disk: false
    secrets: inherit
