name: Deploy IDEM API

on:
  push:
    branches: [main, dev]
    paths:
      - 'apps/api/**'
      - 'apps/ivision/core/**'
      - 'packages/**'
      - 'Dockerfile/prod/Dockerfile.api'
      - '.github/workflows/deploy-api.yml'
      - '.github/workflows/_service.yml'
  pull_request:
    branches: [main, dev]
    paths:
      - 'apps/api/**'
      - 'apps/ivision/core/**'
      - 'packages/**'
      - 'Dockerfile/prod/Dockerfile.api'
      - '.github/workflows/deploy-api.yml'
      - '.github/workflows/_service.yml'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  service:
    uses: ./.github/workflows/_service.yml
    with:
      image: idem-api
      dockerfile: Dockerfile/prod/Dockerfile.api
      service: idem-api
      build-env: false
      deploy: true
      free-disk: true
    secrets: inherit
