name: Deploy iVision web

on:
  push:
    branches: [main, dev]
    paths:
      - 'apps/ivision/web/**'
      - 'packages/**'
      - 'Dockerfile/prod/Dockerfile.ivision-web'
      - '.github/workflows/deploy-ivision-web.yml'
      - '.github/workflows/_service.yml'
  pull_request:
    branches: [main, dev]
    paths:
      - 'apps/ivision/web/**'
      - 'packages/**'
      - 'Dockerfile/prod/Dockerfile.ivision-web'
      - '.github/workflows/deploy-ivision-web.yml'
      - '.github/workflows/_service.yml'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  service:
    uses: ./.github/workflows/_service.yml
    with:
      image: ivision-web
      dockerfile: Dockerfile/prod/Dockerfile.ivision-web
      service: ivision-web
      build-env: true
      deploy: true
      free-disk: false
    secrets: inherit
