name: Deploy AppGen client

on:
  push:
    branches: [main, dev]
    paths:
      - 'apps/appgen/**'
      - 'packages/**'
      - 'Dockerfile/prod/Dockerfile.appgen-client'
      - '.github/workflows/deploy-appgen.yml'
      - '.github/workflows/_service.yml'
      - 'package.json'
      - 'package-lock.json'
  pull_request:
    branches: [main, dev]
    paths:
      - 'apps/appgen/**'
      - 'packages/**'
      - 'Dockerfile/prod/Dockerfile.appgen-client'
      - '.github/workflows/deploy-appgen.yml'
      - '.github/workflows/_service.yml'
      - 'package.json'
      - 'package-lock.json'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  service:
    uses: ./.github/workflows/_service.yml
    with:
      image: appgen-client
      dockerfile: Dockerfile/prod/Dockerfile.appgen-client
      service: appgen-client
      build-env: true
      deploy: true
      free-disk: false
    secrets: inherit
